create table clientes (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  nome VARCHAR(255) NOT NULL,
  email VARCHAR(45) NOT NULL,
  senha VARCHAR(255) NOT NULL,
  cnpj VARCHAR(45) NOT NULL,
  telefone VARCHAR(45) NOT NULL);